spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustc
    username: postgres
    password:
    hikari:
      auto-commit: false
---

benchmark:
  data-path: data
  student-mode: true

