spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: James6112
    hikari:
      auto-commit: false
---

benchmark:
  data-path: data
  student-mode: true

