spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    hikari:
      auto-commit: false;

---

benchmark:
  data-path: data
  student-mode: true
